### PR TITLE
Fixed a few things

### PR DESCRIPTION
**Pull request by Kjagd**

### CODE REVIEW

**Comment by gumbykid** [comment]
I really appreciate you putting in work. I knew there had to be a more
efficient way to change the widgets. I'll test it later today and merge it,
thanks

**Comment by Kjagd** [comment]
No problem :) 
Yea, at least on my computer the clock was running really slowly. Well, I never wrote much
python, so maybe I can learn some from this!

**Comment by gumbykid** [comment]
So "Tkinter" is used in the older versions of python. Make sure your python is updated (I'm using 3.4), and the import will use a lower-case version.

The timer runs quick, I just needed to add some int()'s because you can't format a float - resulting in the timer never updating.

**Comment by Kjagd** [comment]
ah, my bad, I actually thought it was python 2.7!
I think the problem with the old code was that http://effbot.org/tkinterbook/widget.htm#Tkinter.Widget.after-method can be delayed if the system is busy. I guess I'll update to 3.4 and see how it all works out!

**Comment by gumbykid** [comment]
Sounds good. Also, I'm terrible at github (first time), so I ended up
making a new branch and committed the file with the fixes. I'm the future
ill learn how to modify pull requests

**Pull request closed without merging**
